const $ = (selector) => document.querySelector(selector);
const input=$('#messageInput'),send=$('#sendButton'),messages=$('#messages'),welcome=$('#welcome'),statusText=$('#statusText'),orb=$('#orbWrap'),dialog=$('#permissionDialog'),micButton=$('#micButton'),listeningStrip=$('#listeningStrip'),stopListeningButton=$('#stopListening'),wakeToggle=$('#wakeToggle'),wakeStatus=$('#wakeStatus');
let pendingAction=null,listening=false,nativeListenToken=0,wakeEnabled=false,wakeLoopToken=0,localAI={available:false,models:[],selectedModel:null},availableVoices=[],currentConversationId='default',currentLanguage='en';
const VOICE_LANGUAGES=Object.freeze({en:'en-IN',hinglish:'en-IN',hi:'hi-IN',pa:'pa-IN',bn:'bn-IN',mr:'mr-IN',gu:'gu-IN',ta:'ta-IN',te:'te-IN',kn:'kn-IN',ml:'ml-IN',ur:'ur-IN'});
const LANGUAGE_NAMES=Object.freeze({en:'English',hi:'Hindi',hinglish:'Hinglish',pa:'Punjabi',bn:'Bengali',mr:'Marathi',gu:'Gujarati',ta:'Tamil',te:'Telugu',kn:'Kannada',ml:'Malayalam',ur:'Urdu'});
function setState(state='idle',text){const safe=['idle','listening','thinking','speaking','happy'].includes(state)?state:'idle';if(orb)orb.className=`orb-wrap ${safe}`;if(statusText)statusText.textContent=text||({idle:'KRITAM is ready',listening:'KRITAM is listening',thinking:'KRITAM is thinking',speaking:'KRITAM is speaking',happy:'KRITAM is happy'}[safe]);window.kritamDesktop?.setCompanionState?.(safe,text||undefined)?.catch?.(()=>{});}
function addMessage(text,role='assistant',persist=true){if(!text||!messages)return;welcome?.classList.add('hidden');messages.classList.remove('hidden');const item=document.createElement('article');item.className=`message ${role}`;const icon=document.createElement('div');icon.className='message-icon';icon.textContent=role==='assistant'?'K':'YOU';const bubble=document.createElement('div');bubble.className='bubble';bubble.textContent=text;item.append(icon,bubble);messages.append(item);messages.parentElement.scrollTop=messages.parentElement.scrollHeight;if(persist)window.kritamDesktop?.addMemoryMessage?.({conversationId:currentConversationId,role,text}).catch?.(()=>{});}
async function restoreMemory(){try{const history=await window.kritamDesktop?.getRecentMemory?.(currentConversationId,50);if(!Array.isArray(history)||!history.length)return;welcome?.classList.add('hidden');messages?.classList.remove('hidden');messages.innerHTML='';history.forEach(m=>addMessage(m.text,m.role,false));}catch(error){console.warn('Memory restore failed:',error);}}
function toast(text){const node=$('#toast');if(!node)return;node.textContent=text;node.classList.add('show');setTimeout(()=>node.classList.remove('show'),3200);}
function languageCodeFromText(text=''){if(/[\u0A00-\u0A7F]/.test(text))return'pa';if(/[\u0980-\u09FF]/.test(text))return'bn';if(/[\u0A80-\u0AFF]/.test(text))return'gu';if(/[\u0B80-\u0BFF]/.test(text))return'ta';if(/[\u0C00-\u0C7F]/.test(text))return'te';if(/[\u0C80-\u0CFF]/.test(text))return'kn';if(/[\u0D00-\u0D7F]/.test(text))return'ml';if(/[\u0600-\u06FF]/.test(text))return'ur';if(/[\u0900-\u097F]/.test(text))return'hi';if(/\b(hai|haan|bhai|yaar|kya|kaise|kar|karo|mera|meri|mujhe|acha|accha|theek|kholo|chahiye|dikhao|dekhna)\b/i.test(text))return'hinglish';return'en';}
function loadVoices(){if('speechSynthesis'in window)availableVoices=speechSynthesis.getVoices();}
function pickFriendlyVoice(text){if(!availableVoices.length)loadVoices();if(!availableVoices.length)return null;const code=languageCodeFromText(text),locale=VOICE_LANGUAGES[code]||'en-IN',prefix=locale.split('-')[0];const matching=availableVoices.filter(v=>v.lang?.toLowerCase()===locale.toLowerCase()||v.lang?.toLowerCase().startsWith(`${prefix}-`));const pool=matching.length?matching:availableVoices;const female=['jenny','aria','sara','zira','hazel','samantha','heera','neerja','swara','aditi','raveena'];const natural=['online','natural','neural','premium'];const preferred=pool.filter(v=>female.some(n=>v.name?.toLowerCase().includes(n)));return preferred.find(v=>natural.some(n=>v.name?.toLowerCase().includes(n)))||preferred[0]||pool.find(v=>v.default)||pool[0];}
function speak(text){if(!text||!('speechSynthesis'in window))return;speechSynthesis.cancel();const phrase=new SpeechSynthesisUtterance(text),voice=pickFriendlyVoice(text);if(voice){phrase.voice=voice;phrase.lang=voice.lang;}else phrase.lang=VOICE_LANGUAGES[languageCodeFromText(text)]||'en-IN';phrase.rate=.94;phrase.pitch=1.07;phrase.volume=.96;phrase.onstart=()=>setState('speaking','KRITAM is speaking');phrase.onend=()=>setState('idle','KRITAM is ready');phrase.onerror=()=>setState('idle','KRITAM is ready');speechSynthesis.speak(phrase);}
function submitText(text){const value=String(text||'').trim();if(!value||!input)return;input.value=value;send.disabled=false;document.querySelector('#composer')?.requestSubmit();}
async function refreshLocalAI(){if(!window.kritamDesktop?.getOllamaStatus)return;localAI=await window.kritamDesktop.getOllamaStatus().catch(()=>({available:false,models:[]}));const tag=$('#aiTag');if(tag)tag.textContent=!localAI.available?'LOCAL AI: OFF':!localAI.models?.length?'OLLAMA: NO MODEL':`LOCAL AI: ${localAI.selectedModel}`;}
async function askLocalAI(userText){if(!localAI.available)await refreshLocalAI();if(!localAI.available)return null;if(!localAI.models?.length)throw new Error('Ollama is running, but no local model is installed.');const detected=languageCodeFromText(userText);currentLanguage=detected;const recent=[...messages.querySelectorAll('.message')].slice(-8).map(el=>`${el.classList.contains('user')?'user':'assistant'}: ${el.querySelector('.bubble')?.textContent||''}`).join('\n');const system=`You are KRITAM, a private local desktop AI companion. Sound like a warm, intelligent female friend, not customer support. Understand English, Hindi, Hinglish and Indian regional languages. Reply naturally in the user's language and preserve mixed-language speech. Do not force slang or emojis. Keep simple voice replies short and conversational. Never claim a computer action happened unless a tool result confirms it. Detected language: ${LANGUAGE_NAMES[detected]||detected}. Recent context:\n${recent||'(none)'}`;const result=await window.kritamDesktop.ollamaChat([{role:'system',content:system},{role:'user',content:userText}],{model:localAI.selectedModel});return result.message?.trim()||null;}
async function respondWithLocalAI(text){setState('thinking','KRITAM is thinking locally');try{const answer=await askLocalAI(text);if(answer){addMessage(answer);speak(answer);return;}addMessage('I can help with that once a local Ollama model is available.');setState('idle','KRITAM is ready');}catch(error){addMessage(`I couldn’t use the local AI right now. ${error.message||'Please check Ollama.'}`);setState('idle','KRITAM is ready');}}
function actionCard(label,detail,action,buttonText='Allow once'){const el=document.createElement('article');el.className='action-card';const body=document.createElement('div');const title=document.createElement('strong');title.textContent=label;const copy=document.createElement('p');copy.textContent=detail;body.append(title,copy);const button=document.createElement('button');button.type='button';button.textContent=buttonText;button.onclick=()=>askPermission(action);const symbol=document.createElement('span');symbol.textContent='↗';el.append(symbol,body,button);messages.append(el);messages.parentElement.scrollTop=messages.parentElement.scrollHeight;}
function askPermission(action){pendingAction=action;$('#dialogTitle').textContent='Approve this action?';$('#dialogText').textContent=action.description||'KRITAM wants permission before continuing.';$('#dialogDetail').textContent=action.kind||'Desktop action';$('#dialogAction').textContent=action.label||'Action';if(typeof dialog.showModal==='function')dialog.showModal();}
async function runTaskPlan(plan){for(let index=0;index<plan.steps.length;index++){const step=plan.steps[index],sensitive=['type_text','mouse_click','capture_screen','analyze_screen','screen_targets','keyboard_shortcut'].includes(step.tool);if(sensitive){const action={kind:`Task step ${index+1} of ${plan.steps.length} · High risk`,label:step.label||step.tool,description:`KRITAM will perform: ${step.description||step.tool}.`,toolRequest:{tool:step.tool,arguments:step.arguments},taskPlan:plan,taskIndex:index};actionCard(action.label,action.description,action);return;}try{await window.kritamDesktop.executeTool({tool:step.tool,arguments:step.arguments});}catch(error){toast(error.message||'Task step failed.');return;}}addMessage(`Done — all ${plan.steps.length} task steps completed.`);speak(`Done — all ${plan.steps.length} task steps completed.`);}
async function runAction(){if(!pendingAction)return;const action=pendingAction;pendingAction=null;dialog.close();try{if(action.toolRequest){await window.kritamDesktop.executeTool(action.toolRequest);if(action.taskPlan){const next=action.taskIndex+1;if(next<action.taskPlan.steps.length){const step=action.taskPlan.steps[next],nextAction={kind:`Task step ${next+1} of ${action.taskPlan.steps.length} · High risk`,label:step.label||step.tool,description:`KRITAM will perform: ${step.description||step.tool}.`,toolRequest:{tool:step.tool,arguments:step.arguments},taskPlan:action.taskPlan,taskIndex:next};actionCard(nextAction.label,nextAction.description,nextAction);return;}addMessage(`Done — all ${action.taskPlan.steps.length} task steps completed.`);speak(`Done — all ${action.taskPlan.steps.length} task steps completed.`);return;}const message=action.successMessage||`Done — ${action.label||'action'} completed.`;addMessage(message);speak(message);return;}if(action.url){await window.kritamDesktop.openUrl(action.url);const message=`Done — ${action.label||'website'} is opening.`;addMessage(message);speak(message);}}catch(error){toast(error.message||'KRITAM could not complete that action.');}finally{setState('idle','KRITAM is ready');}}
function setListeningUI(active){listening=active;micButton?.classList.toggle('listening',active);listeningStrip?.classList.toggle('active',active);if(stopListeningButton)stopListeningButton.disabled=!active;if(active)setState('listening','KRITAM is listening');else setState('idle','KRITAM is ready');}
async function startVoice(){if(listening)return stopVoice();nativeListenToken+=1;const token=nativeListenToken;setListeningUI(true);try{const result=await window.kritamDesktop?.listenNativeSpeech?.(currentLanguage||'en');if(token!==nativeListenToken)return;const text=result?.text?.trim();if(!text){toast('I didn’t catch that. Try again.');return;}currentLanguage=languageCodeFromText(text);submitText(text);}catch(error){if(token===nativeListenToken)toast(error.message||'Microphone input is unavailable.');}finally{if(token===nativeListenToken)setListeningUI(false);}}
function stopVoice(){nativeListenToken+=1;setListeningUI(false);}
async function startWakeLoop(){if(wakeLoopToken)return;const token=++wakeLoopToken;if(wakeStatus)wakeStatus.textContent='Wake word on';while(wakeEnabled&&token===wakeLoopToken){try{const result=await window.kritamDesktop?.listenNativeSpeech?.('en');if(!wakeEnabled||token!==wakeLoopToken)break;const heard=String(result?.text||'').trim();if(/\bhey\s+kritam\b/i.test(heard)){setState('listening','KRITAM heard you');const remainder=heard.replace(/.*?\bhey\s+kritam\b/i,'').trim();setWakeEnabled(false);if(remainder)submitText(remainder);else await startVoice();}}catch(_){await new Promise(resolve=>setTimeout(resolve,600));}}if(wakeStatus)wakeStatus.textContent='Wake word off';}
function setWakeEnabled(enabled){wakeEnabled=Boolean(enabled);if(wakeToggle)wakeToggle.checked=wakeEnabled;if(wakeEnabled)startWakeLoop();else wakeLoopToken+=1;}
function bindUI(){$('#composer')?.addEventListener('submit',async(event)=>{const text=input?.value?.trim();if(!text){event.preventDefault();return;}addMessage(text,'user');input.value='';send.disabled=true;const handled=await window.kritamConversation?.handle?.(text);if(handled)return;try{const plan=await window.kritamDesktop?.planTask?.(text);if(plan?.type==='task-plan'){runTaskPlan(plan);return;}}catch(error){console.warn('Task planning failed:',error);}await respondWithLocalAI(text);});input?.addEventListener('input',()=>{send.disabled=!input.value.trim();});input?.addEventListener('keydown',(event)=>{if(event.key==='Escape'){speechSynthesis?.cancel?.();stopVoice();}});micButton?.addEventListener('click',startVoice);stopListeningButton?.addEventListener('click',stopVoice);wakeToggle?.addEventListener('change',()=>setWakeEnabled(wakeToggle.checked));$('#newChat')?.addEventListener('click',()=>{messages.innerHTML='';messages.classList.add('hidden');welcome?.classList.remove('hidden');currentConversationId=crypto?.randomUUID?.()||String(Date.now());window.kritamConversation?.clear?.();});$('#approveAction')?.addEventListener('click',runAction);$('#denyAction')?.addEventListener('click',()=>{pendingAction=null;dialog.close();setState('idle','KRITAM is ready');});$('#themeBtn')?.addEventListener('click',()=>document.documentElement.classList.toggle('light'));$('#showCompanion')?.addEventListener('click',()=>window.kritamDesktop?.showCompanion?.());$('#startupToggle')?.addEventListener('change',async(event)=>{try{await window.kritamDesktop?.setLaunchAtLogin?.(event.target.checked);}catch(_){}});$('#privacyBtn')?.addEventListener('click',()=>toast('Privacy controls are active. Sensitive desktop actions require approval.'));document.querySelectorAll('[data-prompt]').forEach(button=>button.addEventListener('click',()=>submitText(button.dataset.prompt)));}
window.addEventListener('DOMContentLoaded',async()=>{bindUI();if('speechSynthesis'in window)speechSynthesis.onvoiceschanged=loadVoices;loadVoices();await restoreMemory();await refreshLocalAI();setState('idle','KRITAM is ready');});
