const $ = (selector) => document.querySelector(selector);
const input = $('#messageInput'), send = $('#sendButton'), messages = $('#messages'), welcome = $('#welcome');
const statusText = $('#statusText'), orb = $('#orbWrap'), dialog = $('#permissionDialog');
let pendingAction = null, recognition = null, listening = false, wakeListening = false, wakeRecognition = null, wakeEnabled = true;
let localAI = { available: false, models: [], selectedModel: null };
let availableVoices = [];
let currentConversationId = 'default';
let currentLanguage = 'en';
const avatarStateText = { idle: 'KRITAM is ready', listening: 'KRITAM is listening', thinking: 'KRITAM is thinking', speaking: 'KRITAM is speaking', happy: 'KRITAM is happy' };
const VOICE_LANGUAGES = Object.freeze({ en:'en-IN', hi:'hi-IN', hinglish:'en-IN', pa:'pa-IN', bn:'bn-IN', mr:'mr-IN', gu:'gu-IN', ta:'ta-IN', te:'te-IN', kn:'kn-IN', ml:'ml-IN', ur:'ur-IN' });
function setState(state, text) { const safeState=['idle','listening','thinking','speaking','happy'].includes(state)?state:'idle'; orb.className=`orb-wrap ${safeState}`; statusText.textContent=text||avatarStateText[safeState]; window.kritamDesktop?.setCompanionState?.(safeState,text||undefined).catch?.(()=>{}); }
function addMessage(text, role='assistant', persist=true) { welcome.classList.add('hidden');messages.classList.remove('hidden');const item=document.createElement('article');item.className=`message ${role}`;const bubble=document.createElement('div');bubble.className='bubble';bubble.textContent=text;const icon=document.createElement('div');icon.className='message-icon';icon.textContent=role==='assistant'?'K':'D';item.append(icon,bubble);messages.append(item);messages.parentElement.scrollTop=messages.parentElement.scrollHeight;if(persist)window.kritamDesktop?.addMemoryMessage?.({conversationId:currentConversationId,role,text}).catch?.(()=>{}); }
async function restoreMemory(){if(!window.kritamDesktop?.getRecentMemory)return;try{const history=await window.kritamDesktop.getRecentMemory(currentConversationId,50);if(!Array.isArray(history)||!history.length)return;welcome.classList.add('hidden');messages.classList.remove('hidden');messages.innerHTML='';history.forEach(m=>addMessage(m.text,m.role,false));}catch(error){console.warn('Memory restore failed:',error);}}
function toast(text){const t=$('#toast');t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3200);}
function loadVoices(){if('speechSynthesis'in window)availableVoices=speechSynthesis.getVoices();}
function languageCodeFromText(text){if(/[\u0A00-\u0A7F]/.test(text))return'pa';if(/[\u0980-\u09FF]/.test(text))return'bn';if(/[\u0A80-\u0AFF]/.test(text))return'gu';if(/[\u0B80-\u0BFF]/.test(text))return'ta';if(/[\u0C00-\u0C7F]/.test(text))return'te';if(/[\u0C80-\u0CFF]/.test(text))return'kn';if(/[\u0D00-\u0D7F]/.test(text))return'ml';if(/[\u0600-\u06FF]/.test(text))return'ur';if(/[\u0900-\u097F]/.test(text))return'hi';if(/\b(hai|haan|bhai|yaar|kya|kaise|kar|karo|mera|meri|mujhe|acha|accha|theek|kholo|chahiye)\b/i.test(text))return'hinglish';return'en';}
function pickFriendlyVoice(text){if(!availableVoices.length)loadVoices();if(!availableVoices.length)return null;const code=languageCodeFromText(text);currentLanguage=code;const locale=VOICE_LANGUAGES[code]||'en-IN';const prefix=locale.split('-')[0].toLowerCase();const matching=availableVoices.filter(v=>v.lang?.toLowerCase()===locale.toLowerCase()||v.lang?.toLowerCase().startsWith(`${prefix}-`));const pool=matching.length?matching:availableVoices;const femaleNames=['jenny','aria','sara','zira','hazel','samantha','female','heera','neerja','swara','aditi','raveena'];const naturalNames=['online','natural','neural','premium'];const female=pool.filter(v=>femaleNames.some(n=>v.name?.toLowerCase().includes(n)));return female.filter(v=>naturalNames.some(n=>v.name?.toLowerCase().includes(n)))[0]||female[0]||pool.find(v=>v.default)||pool[0]||null;}
function speak(text){if(!('speechSynthesis'in window))return;speechSynthesis.cancel();const phrase=new SpeechSynthesisUtterance(text),voice=pickFriendlyVoice(text);if(voice){phrase.voice=voice;phrase.lang=voice.lang;}else phrase.lang=VOICE_LANGUAGES[languageCodeFromText(text)]||'en-IN';phrase.rate=.94;phrase.pitch=1.07;phrase.volume=.96;phrase.onstart=()=>setState('speaking','KRITAM is speaking');phrase.onend=()=>setState('idle','KRITAM is ready');phrase.onerror=()=>setState('idle','KRITAM is ready');speechSynthesis.speak(phrase);}
function respond(text,say=true){setState('thinking','KRITAM is thinking');setTimeout(()=>{addMessage(text);if(say)speak(text);else setState('idle','KRITAM is ready');},520);}
async function refreshLocalAI(){if(!window.kritamDesktop?.getOllamaStatus)return;localAI=await window.kritamDesktop.getOllamaStatus().catch(()=>({available:false,models:[]}));const tag=$('#aiTag');if(!tag)return;tag.textContent=!localAI.available?'LOCAL AI: OFF':!localAI.models?.length?'OLLAMA: NO MODEL':`OLLAMA: ${localAI.selectedModel}`;}
async function askLocalAI(userText){if(!localAI.available)await refreshLocalAI();if(!localAI.available)return null;if(!localAI.models?.length)throw new Error('Ollama is running, but no local model is installed.');const detected=languageCodeFromText(userText);currentLanguage=detected;const languageName={en:'English',hi:'Hindi',hinglish:'Hinglish',pa:'Punjabi',bn:'Bengali',mr:'Marathi',gu:'Gujarati',ta:'Tamil',te:'Telugu',kn:'Kannada',ml:'Malayalam',ur:'Urdu'}[detected]||'the user’s language';const recent=[...messages.querySelectorAll('.message')].slice(-8).map(el=>`${el.classList.contains('user')?'user':'assistant'}: ${el.querySelector('.bubble')?.textContent||''}`).join('\n');const messagesForAI=[{role:'system',content:`You are KRITAM, a privacy-first personal desktop AI companion. You are voice-first and should feel like a warm, intelligent female friend, never like a robotic chatbot or customer-support agent.\n\nLANGUAGE: Understand English, Hindi, Hinglish and Indian regional languages including Punjabi, Bengali, Marathi, Gujarati, Tamil, Telugu, Kannada, Malayalam and Urdu. Respond naturally in the user's language. If they mix languages, preserve the natural mix. Never ask them to choose a language. Detected language: ${languageName}.\n\nPERSONALITY: Sound warm, calm, natural and slightly playful when appropriate. Match the user's formality and energy. Do not force "bhai", slang, emojis or fake enthusiasm. Avoid canned phrases, unnecessary headings and repetitive confirmations. Speak like a familiar helpful friend.\n\nVOICE: Keep spoken replies easy to say aloud. Prefer short natural sentences, contractions and conversational phrasing. Do not write long formal paragraphs for simple voice questions.\n\nCONTEXT: Use the recent conversation below to understand references and continuity.\n${recent||'(no recent context)'}\n\nTRUST: Never claim a desktop action happened unless a tool result confirms it. Sensitive actions remain behind KRITAM's privacy/security controls.`},{role:'user',content:userText}];const result=await window.kritamDesktop.ollamaChat(messagesForAI,{model:localAI.selectedModel});return result.message?.trim()||null;}
async function respondWithLocalAI(text){setState('thinking','KRITAM is thinking locally');try{const answer=await askLocalAI(text);if(answer){addMessage(answer);speak(answer);return;}respond('I can answer that once a local Ollama model is available.');}catch(error){console.error('Local AI error:',error);addMessage(`I couldn't use the local AI right now. ${error.message||'Please check Ollama.'}`);setState('idle','KRITAM is ready');}}
function actionCard(label,detail,action){const el=document.createElement('div');el.className='action-card';el.innerHTML=`<span class="action-symbol">↗</span><div><strong>${label}</strong><p>${detail}</p></div><button>Review & allow</button>`;el.querySelector('button').onclick=()=>askPermission(action);messages.append(el);messages.parentElement.scrollTop=messages.parentElement.scrollHeight;}
function choiceCard(instruction,candidates,context){const el=document.createElement('div');el.className='action-card';el.innerHTML=`<span class="action-symbol">?</span><div><strong>Which one do you mean?</strong><p>I found multiple possible targets for “${instruction}”. Choose one; KRITAM will ask for click approval before acting.</p><div class="target-choices"></div></div>`;const box=el.querySelector('.target-choices');(candidates||[]).slice(0,5).forEach((target,index)=>{const button=document.createElement('button');button.type='button';button.textContent=`${index+1}. ${target.label} (${Math.round(Number(target.confidence||0)*100)}%)`;button.onclick=()=>{const clickAction={kind:'Screen control · High risk',label:`Click “${target.label}”`,description:`You selected “${target.label}”. KRITAM will click only this target after your approval, then verify whether the desktop changed.`,screenClick:{target,imageWidth:context.width,imageHeight:context.height,instruction,fingerprint:context.fingerprint}};askPermission(clickAction);};box.append(button);});messages.append(el);messages.parentElement.scrollTop=messages.parentElement.scrollHeight;}
function askPermission(action){pendingAction=action;$('#dialogTitle').textContent='Approve this action?';$('#dialogText').textContent=action.description;$('#dialogDetail').textContent=action.kind||'Desktop action';$('#dialogAction').textContent=action.label;dialog.showModal();}
function actionFromStep(step,index,total){const risk=step.tool==='type_text'||step.tool==='mouse_click'||step.tool==='capture_screen'||step.tool==='analyze_screen'||step.tool==='screen_targets'||step.tool==='keyboard_shortcut'?'High risk':'Low risk';return{kind:`Task step ${index+1} of ${total} · ${risk}`,label:step.label||step.tool,description:`KRITAM will perform step ${index+1} of ${total}: ${step.description||step.tool}. Only this step will run after approval.`,toolRequest:{tool:step.tool,arguments:step.arguments}};}
async function runTaskPlan(plan){for(let index=0;index<plan.steps.length;index++){const step=plan.steps[index],action=actionFromStep(step,index,plan.steps.length);action.taskPlan=plan;action.taskIndex=index;if(['type_text','mouse_click','capture_screen','analyze_screen','screen_targets','keyboard_shortcut'].includes(step.tool)){actionCard(action.label,action.description,action);return;}try{await window.kritamDesktop.executeTool(action.toolRequest);}catch(error){toast(error.message||'Task step failed.');return;}}}
function isScreenClickCommand(text){return /\b(click|press|select|tap)\b/i.test(String(text||''));}
function createScreenClickAction(instruction){return{kind:'Screen control · High risk',label:'Inspect screen for target',description:`KRITAM wants to inspect your desktop to locate the target for: “${instruction}”. Your screen is only inspected after approval; nothing will be clicked yet.`,screenInstruction:instruction};}
async function executeScreenClickFlow(action){if(!window.kritamDesktop?.findDesktopTargets)throw new Error('Screen control is unavailable in this desktop session.');setState('thinking','Inspecting the desktop…');const result=await window.kritamDesktop.findDesktopTargets(action.screenInstruction);if(result?.selection?.status==='ambiguous'){addMessage('I found multiple possible targets. Please choose the one you mean.');choiceCard(action.screenInstruction,result.selection.candidates,result);setState('idle','KRITAM is ready');return;}const target=result?.selection?.status==='selected'?result.selection.target:null;if(!target){addMessage('I could not find a high-confidence actionable target. I did not click anything.');setState('idle','KRITAM is ready');return;}const clickAction={kind:'Screen control · High risk',label:`Click “${target.label}”`,description:`I found “${target.label}” with ${Math.round(Number(target.confidence)*100)}% confidence. KRITAM will click only that target after your approval, then verify whether the desktop changed.`,screenClick:{target,imageWidth:result.width,imageHeight:result.height,instruction:action.screenInstruction,fingerprint:result.fingerprint}};actionCard(clickAction.label,clickAction.description,clickAction);}
function retryScreenScan(instruction){actionCard('Rescan screen','The desktop may have changed. KRITAM will inspect the screen again only after your approval.',createScreenClickAction(instruction));}
async function runAction(){if(!pendingAction)return;const a=pendingAction;dialog.close();pendingAction=null;try{if(a.screenInstruction){await executeScreenClickFlow(a);return;}if(a.screenClick){setState('thinking','Clicking and verifying…');const result=await window.kritamDesktop.clickDesktopTarget(a.screenClick.target,a.screenClick.imageWidth,a.screenClick.imageHeight,a.screenClick.instruction,a.screenClick.fingerprint);const semantic=result?.semanticVerification;const verification=result?.verification||result?.record?.verification;if(semantic?.success){const message=`Done — clicked “${a.screenClick.target.label}” and visually confirmed the requested result (${Math.round(Number(semantic.confidence)*100)}% confidence).`;addMessage(message);speak(message);}else if(verification==='screen-confirmed'){const message=`Done — clicked “${a.screenClick.target.label}”. The desktop changed, but the requested result could not be semantically confirmed.`;addMessage(message);toast('Screen changed; semantic verification was inconclusive.');setState('idle','KRITAM is ready');}else{addMessage(`I clicked “${a.screenClick.target.label}”, but I could not verify the requested result.`);toast('Action completed, verification was inconclusive.');retryScreenScan(a.screenClick.instruction);setState('idle','KRITAM is ready');}return;}if(a.toolRequest){const result=await window.kritamDesktop.executeTool(a.toolRequest);if(a.taskPlan){const nextIndex=a.taskIndex+1;if(nextIndex<a.taskPlan.steps.length){const next=actionFromStep(a.taskPlan.steps[nextIndex],nextIndex,a.taskPlan.steps.length);next.taskPlan=a.taskPlan;next.taskIndex=nextIndex;actionCard(next.label,next.description,next);toast(`Step ${nextIndex+1} ready for approval.`);return;}const message=`Done — all ${a.taskPlan.steps.length} task steps completed.`;addMessage(message);speak(message);return;}const message=a.successMessage||`Done — ${a.label.replace(/^Open /,'')} completed.`;addMessage(message);speak(message);return;}if(a.url){await window.kritamDesktop.openUrl(a.url);const message=`Done — ${a.label.replace(/^Open /,'')} is opening.`;addMessage(message);speak(message);return;}if(a.camera){requestCamera();addMessage('Done — camera permission request has been sent.');}if(a.done){dialog.close();addMessage(`Done — ${a.done}.`);speak(`Done — ${a.done}.`);}}catch(error){if(/rescan the screen/i.test(error.message||'')){addMessage('The desktop changed before I could safely click. I did not click the stale target.');retryScreenScan(a.screenClick?.instruction||a.screenInstruction||'the requested target');}else toast(error.message||'KRITAM blocked that action.');setState('idle','KRITAM is ready');}}
function requestCamera(){navigator.mediaDevices?.getUserMedia({video:true}).then(stream=>{stream.getTracks().forEach(t=>t.stop());toast('Camera permission was granted, then released.');}).catch(()=>toast('Camera access was not available.'));}
async function tryDesktopCommand(text){if(isScreenClickCommand(text)){actionCard('Inspect screen for target',`KRITAM can locate the target for “${text}” using desktop vision. Your screen will be inspected only after approval.`,createScreenClickAction(text));return true;}if(window.kritamDesktop?.planTask){try{const plan=await window.kritamDesktop.planTask(text);if(plan?.type==='task-plan'){addMessage(`I prepared a ${plan.steps.length}-step plan. I’ll ask for approval before each controlled action.`);runTaskPlan(plan);return true;}}catch(error){console.error('Task planner error:',error);}}if(window.kritamDesktop?.runLocalAgent){try{const result=await window.kritamDesktop.runLocalAgent(text);if(result?.matched){if(result.executed){const data=result.result||{};let message='Done.';if(result.request.tool==='get_time')message=`It’s ${data.local||'the current local time'}.`;else if(result.request.tool==='system_info')message=`Your PC is running ${data.platform||'the current system'} on ${data.arch||'the current architecture'}, with ${data.memoryGB??'?'} GB RAM. CPU: ${data.cpu||'unknown'}.`;else if(result.request.tool==='app_state')message=`${data.app||'That app'} is ${data.running?'running':'not running'}.`;addMessage(message);speak(message);return true;}const request=result.request;actionCard(request.label||'Desktop action',request.description||'KRITAM wants to perform a desktop action.',{kind:`Desktop tool · ${request.policy.risk===2?'High risk':request.policy.risk===1?'Medium risk':'Low risk'}`,label:request.label||request.tool,description:request.description||'KRITAM wants to perform this desktop action.',toolRequest:{tool:request.tool,arguments:request.arguments},successMessage:`Done — ${request.label||request.tool} completed.`});return true;}}catch(error){console.error('Local agent error:',error);}}return false;}
async function interpret(text){const q=text.toLowerCase().trim();if(await tryDesktopCommand(text))return;if(/camera|take\s+(a\s+)?photo/.test(q)){respond('I can use your camera only for the moment you approve.');actionCard('Camera access','One-time permission',{kind:'Sensitive access',label:'Use camera once',description:'KRITAM wants one-time camera access. A visible permission prompt will appear.',camera:true});return;}if(/\b(study|focus)\b/.test(q)){respond('Let’s make it easy: try one 45-minute focus block, then take a 10-minute break. Pick one clear outcome and I’ll help you stay on track.');return;}if(/^(kya chal raha|hello|hi|hey|namaste)\b/.test(q)){respond('Bas ready hoon 😊 Batao, kya karna hai?');return;}await respondWithLocalAI(text);}
function submit(text=input.value.trim()){if(!text)return;addMessage(text,'user');input.value='';send.disabled=true;interpret(text);}
$('#composer').addEventListener('submit',e=>{e.preventDefault();submit();});input.addEventListener('input',()=>send.disabled=!input.value.trim());document.querySelectorAll('[data-prompt]').forEach(b=>b.onclick=()=>{input.value=b.dataset.prompt;submit();});
$('#approveAction').onclick=runAction;$('#denyAction').onclick=()=>{dialog.close();pendingAction=null;toast('Action cancelled. Nothing changed.');};
$('#newChat').onclick=()=>{messages.innerHTML='';messages.classList.add('hidden');welcome.classList.remove('hidden');currentConversationId=`chat-${Date.now()}`;speechSynthesis?.cancel();setState('idle','KRITAM is ready');};
$('#themeBtn').onclick=()=>{document.body.classList.toggle('light');toast('Theme preference saved locally.');};
$('#privacyBtn').onclick=()=>{pendingAction={kind:'Privacy centre',label:'Review permissions',description:'Microphone, camera, files and desktop actions are disabled by default. Each sensitive request needs your approval.',done:'your privacy controls are ready'};askPermission(pendingAction);};
$('#startupToggle').onchange=(event)=>{if(!window.kritamDesktop){event.target.checked=false;toast('Run KRITAM as the desktop app to enable startup.');return;}window.kritamDesktop.setLaunchAtLogin(event.target.checked).then(enabled=>{event.target.checked=enabled;toast(enabled?'KRITAM will start when you sign in.':'Startup launch has been disabled.');});};
$('#showCompanion').onclick=()=>window.kritamDesktop?window.kritamDesktop.showCompanion():toast('Open KRITAM as a desktop app to use the companion.');
function startVoice(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){toast('Voice recognition is not available.');return;}if(listening){recognition.stop();return;}recognition=new SR();recognition.lang=VOICE_LANGUAGES[currentLanguage]||'en-IN';recognition.interimResults=true;recognition.continuous=false;recognition.onstart=()=>{listening=true;$('#micButton').classList.add('listening');setState('listening','Listening…');};recognition.onresult=e=>{const transcript=[...e.results].map(r=>r[0].transcript).join('');input.value=transcript;send.disabled=!transcript.trim();if(e.results[e.results.length-1].isFinal){currentLanguage=languageCodeFromText(transcript);submit(transcript);}};recognition.onerror=()=>{setState('idle','KRITAM is ready');toast('I’m having trouble accessing the microphone.');};recognition.onend=()=>{listening=false;$('#micButton').classList.remove('listening');if(!speechSynthesis?.speaking)setState('idle','KRITAM is ready');};recognition.start();}
$('#micButton').onclick=startVoice;
function stopWakeWord(){wakeEnabled=false;wakeListening=false;try{wakeRecognition?.stop();}catch(_){}wakeRecognition=null;}
function startWakeWord(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR||wakeListening||!wakeEnabled)return false;const wake=new SR();wakeRecognition=wake;wake.lang='en-IN';wake.continuous=true;wake.interimResults=false;wake.onresult=e=>{for(const result of e.results){const phrase=result[0].transcript.trim();if(/\bhey\s+kri?tam\b/i.test(phrase)){setState('listening','Yes? I’m listening');speak('Yes? I’m listening.');startVoice();break;}}};wake.onerror=()=>{wakeListening=false;wakeRecognition=null;if(wakeEnabled)setTimeout(startWakeWord,5000);};wake.onend=()=>{wakeListening=false;wakeRecognition=null;if(wakeEnabled)setTimeout(startWakeWord,1200);};try{wake.start();wakeListening=true;return true;}catch(_){wakeRecognition=null;return false;}}
$('#stopListening').onclick=()=>{recognition?.stop();stopWakeWord();toast('Wake listening is off.');};
window.addEventListener('online',()=>$('#networkTag').textContent='ONLINE');window.addEventListener('offline',()=>{$('#networkTag').textContent='OFFLINE';respond('I’m offline right now, but I can still help with local tasks.');});
window.addEventListener('DOMContentLoaded',()=>{loadVoices();refreshLocalAI();restoreMemory();setTimeout(startWakeWord,1800);});
if('speechSynthesis'in window&&'onvoiceschanged'in speechSynthesis)speechSynthesis.onvoiceschanged=loadVoices;
